name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 1. 打包
  build:
    name: 打包
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 设置Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: 安装依赖项
        run: npm ci
      - name: 使用 VitePress 构建
        run: npm run docs:build
      - name: 上传构件
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 2. 压缩
  optimize:
    name: 压缩
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: 列出文件（调试用）
        run: find docs/.vitepress/dist -type f -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.webp" -o -name "*.gif"
      - name: 检查文件权限
        run: ls -l docs/.vitepress/dist
      - name: 修改文件权限
        run: chmod -R 755 docs/.vitepress/dist
      - name: 压缩图像
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: '70'
          pngQuality: '70'
          webpQuality: '70'
          ignorePaths: '**/node_modules/**'  # 忽略不需要压缩的路径

      - name: 提交更改
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Compressed images" || echo "No changes to commit"
          git push

  # 3. 部署
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: optimize
    runs-on: ubuntu-latest
    name: 部署
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4